services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    volumes:
      - data:/app/data

volumes:
  data:
